# Reusable action for retrieving from cache or compiling
#
# Usage:
# - uses: ./.github/actions/build-app

name: Build and cache application
description: "Build Dotcom assets and compile application"

runs:
  using: "composite"
  steps:
  - uses: ./.github/actions/setup-all
  
  - name: Cache front end assets
    uses: actions/cache@v3
    with:
      path: |
        apps/site/priv/static
        apps/site/react_renderer/dist/app.js
      key: ci-all-assets-cache-${{ hashFiles('apps/site/assets/**', 'apps/site/static/**') }}
    id: assets-cache
 
  - name: Compile front end assets (if needed)
    run: mix compile.assets
    shell: bash
    if: ${{ steps.assets-cache.outputs.cache-hit != 'true' }}
  
  - name: Cache _build
    uses: actions/cache@v3
    with:
      path: _build
      key: ci-build-cache-${{ hashFiles('**/lib/**.ex', '**.exs', '**/mix.lock') }}"
    id: build-cache
  
  - name: Compile application (if needed)
    run: mix compile --all-warnings --warnings-as-errors
    shell: bash
    if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
