name: Update Algolia index

on:
  workflow_call:
  workflow_dispatch:
  schedule: 
    - cron: "0 3 * * *" # every day, 3am

env:
  MIX_ENV: dev
  USE_SERVER_SENT_EVENTS: "false"
  V3_URL: ${{ secrets.V3_URL }}
  V3_API_KEY: ${{ secrets.V3_API_KEY }}
  WARM_CACHES: "false"

jobs:
  algolia:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'mbta'
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-app
    - env:
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_WRITE_KEY: ${{ secrets.ALGOLIA_WRITE_KEY }}
      run: mix algolia.update
