name: Website Crawler

on:
  # Manually select an env to deploy to
  workflow_dispatch:
    inputs:
      deployment-env:
        description: "Environment"
        type: environment # will be prod, dev, dev-blue, or dev-green
        required: true
        default: dev

  workflow_run:
    workflows:
      - "Deploy: master branch"
    types:
      - completed

jobs:
  crawler:
    name: Website Crawler
    runs-on: ubuntu-latest
    env:
      url: ${{ inputs.deployment-env == 'prod' && 'https://www.mbta.com' || format('https://{0}.mbtace.com', inputs.deployment-env || 'dev') }}
    
    steps:
    - uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
    - name: Run Crawler
      run: |
        mix escript.install --force github mbta/link_checker
        $HOME/.mix/escripts/crawler ${{ env.url }} --num-workers 3
