name: Asana Workflow

on:
  pull_request:
    types: [closed, edited, opened, review_requested, ready_for_review, reopened, synchronize]

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/asana.yml@e7f8691b3f876ea9cd73b50a0a6131d8ad2afb9e
    with:
      complete-on-merge: false
      review-section: "Code/Design Review"
      merged-section: "To Be Released"
      attach-pr: true
      trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
    secrets:
      asana-token: ${{ secrets.ASANA_PERSONAL_ACCESS_TOKEN }}
      github-secret: ${{ secrets.ASANA_SECRET }}
