name: Asana Workflow

on:
  pull_request:
    types: [review_requested, closed]

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/asana.yml@1c8f002ddb10ea4b353bc3a485661d2d8b0f102e
    with:
      complete-on-merge: false
      review-section: "Code/Design Review"
      merged-section: "To Be Released"
      attach-pr: true
      trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
    secrets:
      asana-token: ${{ secrets.ASANA_PERSONAL_ACCESS_TOKEN }}
      github-secret: ${{ secrets.ASANA_SECRET }}
