# Deploy to dev on merge or push into main
name: "Deploy: main branch"

on:
  push:
    branches: [main]

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  auto:
    uses: ./.github/workflows/use-deploy-ecs.yml
    with:
      deployment-env: dev
    secrets:
      aws-account-id: ${{ secrets.TID_AWS_ACCOUNT_ID }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}

  notify:
    needs: [auto]
    uses: ./.github/workflows/use-notify-slack.yml
    if: ${{ !cancelled() }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      job-status: ${{ needs.auto.result }}
      success-message: |
        :ballot_box_with_check: `dev` updated to latest commit on main
      failure-message: |
        :ballot_box_with_check: `dev` not updated to latest commit on main
