name: Deploy Monitor

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: mbta/actions/build-push-ecr@v2
        with:
          docker-repo: "${{ secrets.monitor-docker-repo }}"
          dockerfile-path: ./deploy/monitor/Dockerfile
          role-to-assume: ${{ secrets.aws-role-arn }}
