name: Deploy to ECS

on:
  # Manually select an environment to deploy to
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment # will be prod, dev, dev-blue, or dev-green
        required: true
        default: dev-blue
  # push:
  #   branches: [master]

concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: true

jobs:
  # TODO: Check if image is already there for this ref?
  deploy:
    if: ${{ github.event.inputs.environment != 'dev' && github.event.inputs.environment != 'prod' }}
    name: Build image, push to ECR, deploy to ECS
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-18.04 # ubuntu-latest causes aws-cli command in upload_assets.sh to fail -- see https://github.com/aws/aws-cli/issues/5262
    outputs:
      docker-tag: ${{ steps.build-push.outputs.docker-tag }}
    steps:
      - uses: actions/checkout@v3
      - run: echo '# Deploying ${{ github.ref }} to ${{ github.event.inputs.environment }} :rocket:' >> $GITHUB_STEP_SUMMARY
      - uses: mbta/actions/build-push-ecr@v1
        id: build-push
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
      - run: echo '- Built docker image and uploaded ${{ steps.build-push.outputs.docker-tag }} to ECR.' >> $GITHUB_STEP_SUMMARY
      - run: bash upload_assets.sh ${{ steps.build-push.outputs.docker-tag }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: echo '- Uploaded assets from ${{ steps.build-push.outputs.docker-tag }} to S3.' >> $GITHUB_STEP_SUMMARY
      - uses: mbta/actions/deploy-ecs@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecs-cluster: dotcom
          ecs-service: ${{ secrets.ECS_SERVICE }} # depends on selected environment
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
      - run: echo '- Deployed ${{ steps.build-push.outputs.docker-tag }} to ECS.' >> $GITHUB_STEP_SUMMARY

  notify:
    if: ${{ github.event.inputs.environment != 'dev' && github.event.inputs.environment != 'prod' }}
    needs: [deploy]
    name: Send notification to Slack
    runs-on: ubuntu-latest

    steps:
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ needs.deploy.result }}
          custom-message: |
            `${{ github.ref }}` deployment to Dotcom ${{ github.event.inputs.environment }}
