# Experimental!

name: Deploy to Dev Elastic Beanstalk

on:
  # manually start
  workflow_dispatch:
  # push:
    # branches: [$default_branch]

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest

    # The environment specifies ELASTICBEANSTALK_ APP_NAME & ENV_NAME
    environment: dev
    
    concurrency: dev
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v2
      - id: metadata
        uses: mbta/actions/commit-metadata@v1
      
      # Build a Docker image and push to ECR, outputs docker-tag
      - id: build-push
        uses: mbta/actions/build-push-ecr@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
    
      # Build an Elastic Beanstalk Dockerrun.aws.json based on an AWS ECR tag
      - id: deployment-package
        uses: mbta/actions/eb-ecr-dockerrun@v1
        with:
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
      
      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: mbta/beanstalk-deploy@v18
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application-name: ${{ secrets.ELASTICBEANSTALK_APP_NAME}}
          environment-name: ${{ secrets.ELASTICBEANSTALK_ENV_NAME }}
          version-label: ${{ steps.metadata.outputs.sha-short }}
          version-description: ${{ steps.metadata.outputs.commit-message }}
          region: ${{ env.AWS_REGION }}
          deployment-package: ${{ steps.deployment-package.outputs.deployment-package }}
          use-existing-version-if-available: true
      
      # Send notifications!
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
