# Deploys chosen branch to chosen environment
name: "Deploy: selected branch"

on:
  # Manually select an env to deploy to
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: environment # will be prod, dev, dev-blue, or dev-green
        required: true
        default: dev-blue

jobs:
  branch:
    uses: ./.github/workflows/use-deploy-ecs.yml
    with:
      deployment-env: ${{ github.event.inputs.env }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.DOCKER_REPO }}

  notify:
    needs: [branch]
    uses: ./.github/workflows/use-notify-slack.yml
    if: ${{ !cancelled() }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      job-status: ${{ needs.branch.result }}
      success-message: |
        `${{ github.ref_name }}` branch manually deployed to `${{ github.event.inputs.env }}`
      failure-message: |
        `${{ github.ref_name }}` branch not deployed to `${{ github.event.inputs.env }}`
