# Deploy to dev on merge or push into master
name: "Deploy: master branch"

on:
  push:
    branches: [master]

jobs:
  auto:
    uses: ./.github/workflows/use-deploy-ecs.yml
    with:
      deployment-env: dev
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

  notify:
    needs: [auto]
    uses: ./.github/workflows/use-notify-slack.yml
    if: ${{ !cancelled() }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      job-status: ${{ needs.auto.result }}
      success-message: |
        :ballot_box_with_check: `dev` updated to latest commit on master
      failure-message: |
        :ballot_box_with_check: `dev` not updated to latest commit on master
