name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev
    env:
      AWS_REGION: us-east-1
      ELASTICBEANSTALK_APPLICATION_NAME: dotcom
      ELASTICBEANSTALK_ENVIRONMENT_NAME: dotcom-dev

    steps:
      - uses: actions/checkout@v2
      - id: metadata
        uses: mbta/actions/commit-metadata@v1
      - uses: mbta/actions/build-push-ecr@v1
        id: build-push
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
      - name: Upload static assets to S3
        run: bash upload_assets.sh ${{ steps.build-push.outputs.docker-tag }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: deployment-package
        uses: mbta/actions/eb-ecr-dockerrun@v1
        with:
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
      - name: Deploy to EB
        uses: mbta/beanstalk-deploy@v18
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application-name: ${{ env.ELASTICBEANSTALK_APPLICATION_NAME }}
          environment-name: ${{ env.ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          version-label: ${{ steps.metadata.outputs.sha-short }}
          version-description: ${{ steps.metadata.outputs.commit-message }}
          region: ${{ env.AWS_REGION }}
          deployment-package: ${{ steps.deployment-package.outputs.deployment-package }}
          use-existing-version-if-available: true
      - name: Run Crawler
        run: |
          mix escript.install --force https://s3.amazonaws.com/mbta-dotcom/crawler
          $HOME/.mix/escripts/crawler https://dev.mbtace.com --num-workers 3
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
