name: Docker

on: 
  push:
    paths-ignore: 
      - ".github/workflows/**"
      - "*.md"
      - "integration/**"

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build .
