name: Docker build
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build .
