name: Push Sidecar

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build, tag, and push image to Amazon ECR
        uses: mbta/actions/build-push-ecr@v2
        with:
          docker-repo: "${{ secrets.SIDECAR_DOCKER_REPO }}"
          dockerfile-path: "-f ./deploy/sidecar/Dockerfile ."
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
