name: Shellcheck
on: 
  pull_request:
    paths:
      - "*.sh"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
